name: Passwort Beispiel

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Passwort verwenden
        run: echo "Login wird durchgeführt"
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
